### ISSUE TITLE
set plot printing global option

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/subfoldr2#101]
running into R crash errors during sbf_open_window() / sbf_print()
can set global option in header to indicate whether to skip printing plots
similar to `set_analysis_mode()`

name?
`set_plot_print_mode()`?

**Comment by sebdalgarno** [comment]
or maybe `sbf_print_plots()` with TRUE/FALSE as only input options

**Comment by joethorley** [comment]
Nice - that works for me.

**Comment by sebdalgarno** [comment]
actually much simpler to follow the precedent of sbf.ask, i.e. setting in header.R
```
options(sbf.plot = FALSE)
```

**Comment by joethorley** [comment]
Perfect -  @sebdalgarno do you have time to implement?
