### ISSUE TITLE
deprecate the *_exist family of functions

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/subfoldr2#58]
Deprecate these functions: 
  - '`sbf_block_exists`'
  - '`sbf_data_exists`'
  - '`sbf_number_exists`'
  - '`sbf_object_exists`'
  - '`sbf_plot_exists`'
  - '`sbf_string_exists`'
  - '`sbf_table_exists`'

Only `sbf_object_exists()` is being used in a couple scripts so we have decided to deprecate these functions.

We will be at the first stage of deprecation, use this to help guide which stage/level of deprecation https://lifecycle.r-lib.org/reference/deprecate_soft.html . There are examples in the chk package in the R/deprecated.R file.

Since all the exists functions are in their own script just do the deprecation there (ie no need to move to a deprecated.R script)

**Comment by joethorley** [comment]
done by Alan
