### ISSUE TITLE
Can't install subfoldr2 without access to private Poisson repos

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/subfoldr2#80]
When installing with `remotes::install_github`, it first tries to install `readwriteaws` which is private.
`readwriteaws` is under Suggests and Remotes - I'm not sure why remotes is checking it.

Default value of `dependencies` arg in `install_github` is NA - which checks for "Depends", "Imports" and "LinkingTo"
not "Suggests"

This could be a bug in remotes

Workaround is to install previous version prior to readwriteaws `install_github("poissonconsulting/[subfoldr2@v0.0.0.9045](mailto:subfoldr2@v0.0.0.9045)")`

Potentially could make readwriteaws public

**Comment by joethorley** [comment]
readwriteaws is now public
